// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComputerTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250509141755_09_05_2025_1")]
    partial class _09_05_2025_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComputerTracker.Data.DbModel.AppUsageEntry", b =>
                {
                    b.Property<int>("AppUsageEntryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppUsageEntryID"));

                    b.Property<int>("ComputerId")
                        .HasColumnType("int");

                    b.Property<int?>("ComputerSystemDataSystemDataID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("WindowTitle")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("AppUsageEntryID");

                    b.HasIndex("ComputerId");

                    b.HasIndex("ComputerSystemDataSystemDataID");

                    b.ToTable("AppUsageEntries");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.Computer", b =>
                {
                    b.Property<int>("ComputerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComputerID"));

                    b.Property<string>("ComputerName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.HasKey("ComputerID");

                    b.HasIndex("IPAddress")
                        .IsUnique();

                    b.HasIndex("Host", "Port")
                        .IsUnique();

                    b.ToTable("Computers");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.ComputerGpu", b =>
                {
                    b.Property<int>("ComputerGpuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComputerGpuID"));

                    b.Property<long>("AdapterRAM")
                        .HasColumnType("bigint");

                    b.Property<int>("ComputerId")
                        .HasColumnType("int");

                    b.Property<int?>("ComputerSystemDataSystemDataID")
                        .HasColumnType("int");

                    b.Property<string>("DriverVersion")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("ComputerGpuID");

                    b.HasIndex("ComputerId");

                    b.HasIndex("ComputerSystemDataSystemDataID");

                    b.ToTable("Gpus");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.ComputerSystemData", b =>
                {
                    b.Property<int>("SystemDataID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SystemDataID"));

                    b.Property<string>("CPUName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("ComputerID")
                        .HasColumnType("int");

                    b.Property<int>("CpuClockMHz")
                        .HasColumnType("int");

                    b.Property<int>("CpuCores")
                        .HasColumnType("int");

                    b.Property<int>("CpuThreads")
                        .HasColumnType("int");

                    b.Property<string>("OSCaption")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("OSManufacturer")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("OSVersion")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("WindowsDirectory")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("SystemDataID");

                    b.HasIndex("ComputerID");

                    b.ToTable("ComputerSystemDatas");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("DepartmentID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("EmployeeID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.KeyLogEntry", b =>
                {
                    b.Property<int>("KeyLogEntryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KeyLogEntryID"));

                    b.Property<int>("ComputerId")
                        .HasColumnType("int");

                    b.Property<int?>("ComputerSystemDataSystemDataID")
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("KeyLogEntryID");

                    b.HasIndex("ComputerId");

                    b.HasIndex("ComputerSystemDataSystemDataID");

                    b.ToTable("KeyLogEntries");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.Keyboard", b =>
                {
                    b.Property<int>("KeyboardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KeyboardID"));

                    b.Property<int>("ComputerId")
                        .HasColumnType("int");

                    b.Property<int?>("ComputerSystemDataSystemDataID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("DeviceID")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("KeyboardID");

                    b.HasIndex("ComputerId");

                    b.HasIndex("ComputerSystemDataSystemDataID");

                    b.ToTable("Keyboards");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.Monitor", b =>
                {
                    b.Property<int>("MonitorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonitorID"));

                    b.Property<int>("ComputerId")
                        .HasColumnType("int");

                    b.Property<int?>("ComputerSystemDataSystemDataID")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("MonitorID");

                    b.HasIndex("ComputerId");

                    b.HasIndex("ComputerSystemDataSystemDataID");

                    b.ToTable("Monitors");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.Mouse", b =>
                {
                    b.Property<int>("MouseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MouseID"));

                    b.Property<int>("ComputerId")
                        .HasColumnType("int");

                    b.Property<int?>("ComputerSystemDataSystemDataID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("DeviceID")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("MouseID");

                    b.HasIndex("ComputerId");

                    b.HasIndex("ComputerSystemDataSystemDataID");

                    b.ToTable("Mice");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.Printer", b =>
                {
                    b.Property<int>("PrinterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrinterID"));

                    b.Property<int>("ComputerId")
                        .HasColumnType("int");

                    b.Property<int?>("ComputerSystemDataSystemDataID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("PrinterID");

                    b.HasIndex("ComputerId");

                    b.HasIndex("ComputerSystemDataSystemDataID");

                    b.ToTable("Printers");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.Scanner", b =>
                {
                    b.Property<int>("ScannerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScannerID"));

                    b.Property<int>("ComputerId")
                        .HasColumnType("int");

                    b.Property<int?>("ComputerSystemDataSystemDataID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("ScannerID");

                    b.HasIndex("ComputerId");

                    b.HasIndex("ComputerSystemDataSystemDataID");

                    b.ToTable("Scanners");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.Software", b =>
                {
                    b.Property<int>("SoftwareID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoftwareID"));

                    b.Property<string>("SoftwareName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("SoftwareID");

                    b.ToTable("Softwares");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.SoftwareUsage", b =>
                {
                    b.Property<int>("SoftwareUsageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoftwareUsageID"));

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionID")
                        .HasColumnType("int");

                    b.Property<int>("SoftwareID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("SoftwareUsageID");

                    b.HasIndex("SessionID");

                    b.HasIndex("SoftwareID");

                    b.ToTable("SoftwareUsages");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.UsageSession", b =>
                {
                    b.Property<int>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionID"));

                    b.Property<int>("ComputerID")
                        .HasColumnType("int");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("SessionID");

                    b.HasIndex("ComputerID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("UsageSessions", t =>
                        {
                            t.HasTrigger("trg_CalcSessionDuration");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.AppUsageEntry", b =>
                {
                    b.HasOne("ComputerTracker.Data.DbModel.Computer", "Computer")
                        .WithMany("AppUsageEntries")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerTracker.Data.DbModel.ComputerSystemData", null)
                        .WithMany("AppUsage")
                        .HasForeignKey("ComputerSystemDataSystemDataID");

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.ComputerGpu", b =>
                {
                    b.HasOne("ComputerTracker.Data.DbModel.Computer", "Computer")
                        .WithMany("Gpus")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerTracker.Data.DbModel.ComputerSystemData", null)
                        .WithMany("Gpus")
                        .HasForeignKey("ComputerSystemDataSystemDataID");

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.ComputerSystemData", b =>
                {
                    b.HasOne("ComputerTracker.Data.DbModel.Computer", "Computer")
                        .WithMany("SystemData")
                        .HasForeignKey("ComputerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.Employee", b =>
                {
                    b.HasOne("ComputerTracker.Data.DbModel.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.KeyLogEntry", b =>
                {
                    b.HasOne("ComputerTracker.Data.DbModel.Computer", "Computer")
                        .WithMany("KeyLogEntries")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerTracker.Data.DbModel.ComputerSystemData", null)
                        .WithMany("KeyLog")
                        .HasForeignKey("ComputerSystemDataSystemDataID");

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.Keyboard", b =>
                {
                    b.HasOne("ComputerTracker.Data.DbModel.Computer", "Computer")
                        .WithMany("Keyboards")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerTracker.Data.DbModel.ComputerSystemData", null)
                        .WithMany("Keyboards")
                        .HasForeignKey("ComputerSystemDataSystemDataID");

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.Monitor", b =>
                {
                    b.HasOne("ComputerTracker.Data.DbModel.Computer", "Computer")
                        .WithMany("Monitors")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerTracker.Data.DbModel.ComputerSystemData", null)
                        .WithMany("Monitors")
                        .HasForeignKey("ComputerSystemDataSystemDataID");

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.Mouse", b =>
                {
                    b.HasOne("ComputerTracker.Data.DbModel.Computer", "Computer")
                        .WithMany("Mice")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerTracker.Data.DbModel.ComputerSystemData", null)
                        .WithMany("Mice")
                        .HasForeignKey("ComputerSystemDataSystemDataID");

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.Printer", b =>
                {
                    b.HasOne("ComputerTracker.Data.DbModel.Computer", "Computer")
                        .WithMany("Printers")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerTracker.Data.DbModel.ComputerSystemData", null)
                        .WithMany("Printers")
                        .HasForeignKey("ComputerSystemDataSystemDataID");

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.Scanner", b =>
                {
                    b.HasOne("ComputerTracker.Data.DbModel.Computer", "Computer")
                        .WithMany("Scanners")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerTracker.Data.DbModel.ComputerSystemData", null)
                        .WithMany("Scanners")
                        .HasForeignKey("ComputerSystemDataSystemDataID");

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.SoftwareUsage", b =>
                {
                    b.HasOne("ComputerTracker.Data.DbModel.UsageSession", "Session")
                        .WithMany("SoftwareUsages")
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerTracker.Data.DbModel.Software", "Software")
                        .WithMany("SoftwareUsages")
                        .HasForeignKey("SoftwareID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.UsageSession", b =>
                {
                    b.HasOne("ComputerTracker.Data.DbModel.Computer", "Computer")
                        .WithMany("UsageSessions")
                        .HasForeignKey("ComputerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerTracker.Data.DbModel.Employee", "Employee")
                        .WithMany("UsageSessions")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Computer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.Computer", b =>
                {
                    b.Navigation("AppUsageEntries");

                    b.Navigation("Gpus");

                    b.Navigation("KeyLogEntries");

                    b.Navigation("Keyboards");

                    b.Navigation("Mice");

                    b.Navigation("Monitors");

                    b.Navigation("Printers");

                    b.Navigation("Scanners");

                    b.Navigation("SystemData");

                    b.Navigation("UsageSessions");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.ComputerSystemData", b =>
                {
                    b.Navigation("AppUsage");

                    b.Navigation("Gpus");

                    b.Navigation("KeyLog");

                    b.Navigation("Keyboards");

                    b.Navigation("Mice");

                    b.Navigation("Monitors");

                    b.Navigation("Printers");

                    b.Navigation("Scanners");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.Employee", b =>
                {
                    b.Navigation("UsageSessions");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.Software", b =>
                {
                    b.Navigation("SoftwareUsages");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.UsageSession", b =>
                {
                    b.Navigation("SoftwareUsages");
                });
#pragma warning restore 612, 618
        }
    }
}
