// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComputerTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComputerTracker.Data.DbModel.Computer", b =>
                {
                    b.Property<int>("ComputerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComputerID"));

                    b.Property<string>("ComputerName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("ComputerID");

                    b.HasIndex("IPAddress")
                        .IsUnique();

                    b.ToTable("Computers");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.ComputerSystemData", b =>
                {
                    b.Property<int>("SystemDataID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SystemDataID"));

                    b.Property<double>("CPUUsage")
                        .HasColumnType("float");

                    b.Property<int>("ComputerID")
                        .HasColumnType("int");

                    b.Property<double>("DiskUsage")
                        .HasColumnType("float");

                    b.Property<double>("MemoryUsage")
                        .HasColumnType("float");

                    b.Property<double>("NetworkUsage")
                        .HasColumnType("float");

                    b.Property<string>("OSVersion")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("SystemDataID");

                    b.HasIndex("ComputerID");

                    b.ToTable("ComputerSystemDatas");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("DepartmentID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("EmployeeID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.Software", b =>
                {
                    b.Property<int>("SoftwareID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoftwareID"));

                    b.Property<string>("SoftwareName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("SoftwareID");

                    b.ToTable("Softwares");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.SoftwareUsage", b =>
                {
                    b.Property<int>("SoftwareUsageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoftwareUsageID"));

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionID")
                        .HasColumnType("int");

                    b.Property<int>("SoftwareID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("SoftwareUsageID");

                    b.HasIndex("SessionID");

                    b.HasIndex("SoftwareID");

                    b.ToTable("SoftwareUsages");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.UsageSession", b =>
                {
                    b.Property<int>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionID"));

                    b.Property<int>("ComputerID")
                        .HasColumnType("int");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("SessionID");

                    b.HasIndex("ComputerID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("UsageSessions", t =>
                        {
                            t.HasTrigger("trg_CalcSessionDuration");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.ComputerSystemData", b =>
                {
                    b.HasOne("ComputerTracker.Data.DbModel.Computer", "Computer")
                        .WithMany("SystemData")
                        .HasForeignKey("ComputerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.Employee", b =>
                {
                    b.HasOne("ComputerTracker.Data.DbModel.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.SoftwareUsage", b =>
                {
                    b.HasOne("ComputerTracker.Data.DbModel.UsageSession", "Session")
                        .WithMany("SoftwareUsages")
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerTracker.Data.DbModel.Software", "Software")
                        .WithMany("SoftwareUsages")
                        .HasForeignKey("SoftwareID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.UsageSession", b =>
                {
                    b.HasOne("ComputerTracker.Data.DbModel.Computer", "Computer")
                        .WithMany("UsageSessions")
                        .HasForeignKey("ComputerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerTracker.Data.DbModel.Employee", "Employee")
                        .WithMany("UsageSessions")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Computer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.Computer", b =>
                {
                    b.Navigation("SystemData");

                    b.Navigation("UsageSessions");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.Employee", b =>
                {
                    b.Navigation("UsageSessions");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.Software", b =>
                {
                    b.Navigation("SoftwareUsages");
                });

            modelBuilder.Entity("ComputerTracker.Data.DbModel.UsageSession", b =>
                {
                    b.Navigation("SoftwareUsages");
                });
#pragma warning restore 612, 618
        }
    }
}
